 export const dataitems = [
    {"id": "LNMCHM001", "name": "Chalk"},
    {"id": "LNMCHM002", "name": "Blackboard"},
    {"id": "LNMCHM003", "name": "Dusters"},
    {"id": "LNMCHM004", "name": "WhiteBoard Marker"},
    {"id": "LNMCHM005", "name": "WhiteBoard Eraser"},
    {"id": "LNMCHM006", "name": "Desks"},
    {"id": "LNMCHM007", "name": "Chair"},
    {"id": "LNMCHM008", "name": "Projector"},
    {"id": "LNMCHM009", "name": "Projector Screen"},
    {"id": "LNMCHM010", "name": "Computer"},
    {"id": "LNMCHM011", "name": "Mouse"},
    {"id": "LNMCHM012", "name": "Keyboard"},
    {"id": "LNMCHM013", "name": "Clock"},
    {"id": "LNMCHM014", "name": "Trash bin"},
    {"id": "LNMCHM015", "name": "Fan"},
    {"id": "LNMCHM016", "name": "Air Conditioner"},
    {"id": "LNMCHM017", "name": "Curtain/Blinds"},
    {"id": "LNMCHM018", "name": "Bed"},
    {"id": "LNMCHM019", "name": "Study Table"},
    {"id": "LNMCHM020", "name": "Room Curtain"},
    {"id": "LNMCHM021", "name": "Mirror"},
    {"id": "LNMCHM022", "name": "Towel racks"},
    {"id": "LNMCHM023", "name": "Air Freshners"},
    {"id": "LNMCHM024", "name": "Wall Calenders"},
    {"id": "LNMCHM025", "name": "Water coolers"},
    {"id": "LNMCHM026", "name": "Softboard"}
]